image: joaodubas/nodejs
env:
    - LVLDB_HOST=db
    - LVLDB_PORT=3001
script:
    - cd app
    - npm install
    - npm test
services:
    - joaodubas/multilevel
notify:
    email:
        recipients:
            - joao.dubas@gmail.com
